// V2.25 Task 2 — Automatic Daily Report generation. Confirmed real gap: a Daily Report
// (store.ts's generateDailyReport / DailyReportSnapshot) only ever came into existence when the
// user explicitly opened Close Day and clicked "Generate" — an install that never opens that
// modal on a given day simply has no report for it, even though real memoryEvents (completed
// actions, and now Jira-detected completions — see jira-completion-detection.ts) genuinely
// happened that day. Close Day itself is untouched: it stays the review/confirm surface,
// generateDailyReport(dateIso, force) is the exact same method it already calls.
//
// Two triggers cover "on app load or sync" (per this task's spec), reusing generateDailyReport
// itself in both cases — never a second report-generation path:
//  1. This module's own initAutoDailyReport (below), run once per app session from the same
//     single mount point auto-sync.ts uses (Nav.tsx) — covers Demo/Local Import installs and a
//     Jira install whose data is still "fresh" enough that auto-sync.ts's own tick is a no-op.
//  2. store.ts's syncJira() itself calls generateDailyReport directly at the end of a
//     successful sync (see that method's own comment) — covers the case this module can't:
//     freshly-detected JIRA_STATUS_COMPLETED events from THIS sync need to be reflected
//     immediately, not on the next page load.

import type { CommandCenterStore } from "./store";
import { todayLocalIso } from "./date-utils";
import type { DailyReportSnapshot } from "./types";

/** Pure: the day has "rolled over" for report purposes when the most recently generated
 *  report's date isn't today — covers both "no report has ever been generated" (empty
 *  dailyReports) and "today's report doesn't exist yet because the calendar day just changed
 *  since the last one was made". Never regenerates an already-current today's report on every
 *  call — `dailyReports` keys are ISO dates, so string-sorting them is a safe way to find the
 *  latest without assuming insertion order. */
export function shouldAutoGenerateDailyReport(today: string, dailyReports: Record<string, DailyReportSnapshot>): boolean {
  const mostRecent = Object.keys(dailyReports).sort().at(-1);
  return mostRecent !== today;
}

let initialized = false;

/** Called once per app session (idempotent — safe to call from every page mount), mirroring
 *  initAutoJiraSync's own module-level guard exactly. No interval timer here (unlike
 *  auto-sync.ts): a day only rolls over once, and every real sync already re-checks via
 *  store.syncJira() itself — a periodic re-check of this specific condition would just be
 *  redundant polling for an event that fires at most once per calendar day per session. */
export function initAutoDailyReport(store: CommandCenterStore): void {
  if (initialized) return;
  initialized = true;

  const state = store.getSnapshot();
  if (!state.loaded) return; // nothing meaningful to report before any data has loaded
  const today = todayLocalIso();
  if (shouldAutoGenerateDailyReport(today, state.dailyReports)) store.generateDailyReport(today, true);
}

/** Test-only reset — mirrors resetAutoJiraSyncForTests' own purpose: lets the offline test
 *  suite exercise initAutoDailyReport's guard without cross-contaminating other test cases via
 *  leftover module state. */
export function resetAutoDailyReportForTests(): void {
  initialized = false;
}
