// V1.3 — live Jira ingestion: mapping, normalization, pagination, filters, freshness, query routing
// Run through scripts/tests/run.mts (npm test).

import { detectChanges, toSnapshot } from "../../src/lib/command-center/change-detection";
import { buildDemoData } from "../../src/lib/command-center/demo-data";
import { emptyData } from "../../src/lib/command-center/types";
import { MockAIProvider } from "../../src/lib/command-center/ai/provider";
import { commandCenterStore } from "../../src/lib/command-center/store";
import { mapPriority, mapStatus, mapWorkItemType, isBlockedByHeuristic } from "../../src/lib/command-center/jira/mapping";
import { normalizeIssue, normalizeIssues, normalizeProjects, clientIdForProjectKey } from "../../src/lib/command-center/jira/normalize";
import { jiraIssueSchema, jiraSearchResponseSchema } from "../../src/lib/command-center/jira/types";
import { fetchJiraIssuesWith, fetchJiraProjectsWith, buildIssuesJql, classifyHttpError, JIRA_PAGE_SIZE, type FetchLike } from "../../src/lib/command-center/jira/http";
import { DisabledJiraActionProvider } from "../../src/lib/command-center/jira/jira-action-provider";
import { applyFilters, availableFixVersions } from "../../src/lib/command-center/filters";
import { computeFreshness } from "../../src/lib/command-center/freshness";
import { computeReleaseHealth, computeAllReleaseHealth } from "../../src/lib/command-center/release-health";
import { classifyQuery, answerFromRoute } from "../../src/lib/command-center/query-router";
import { JiraDataSource } from "../../src/lib/command-center/datasource/jira-source";
import { deriveData } from "../../src/lib/command-center/selectors";
import fs from "node:fs";
import path from "node:path";
import { shouldAutoSyncJira } from "../../src/lib/command-center/auto-sync";
import type { JiraSyncState } from "../../src/lib/command-center/types";
import { shouldAutoGenerateDailyReport } from "../../src/lib/command-center/auto-daily-report";
import { ok } from "./harness.mts";
import { TODAY, makeItem, makeJiraIssue } from "./helpers.mts";

// ===== Jira priority / status / type mapping =====
{
  ok("Jira mapping", mapPriority("Highest") === "P1" && mapPriority("Blocker") === "P1", "Highest/Blocker map to P1");
  ok("Jira mapping", mapPriority("High") === "P2", "High maps to P2");
  ok("Jira mapping", mapPriority("Medium") === "P3", "Medium maps to P3");
  ok("Jira mapping", mapPriority("Low") === "P4" && mapPriority("Lowest") === "P4", "Low/Lowest map to P4");
  ok("Jira mapping", mapPriority(undefined) === "P3", "missing priority defaults to P3, never P1 (never fabricated urgency)");
  ok("Jira mapping", mapPriority("Custom-Severity-9") === "P3", "an unrecognized custom priority name falls back to P3 rather than throwing");

  ok("Jira mapping", mapStatus("To Do", "new", false) === "Not Started", "statusCategory 'new' maps to Not Started");
  ok("Jira mapping", mapStatus("In Progress", "indeterminate", false) === "In Progress", "statusCategory 'indeterminate' maps to In Progress");
  ok("Jira mapping", mapStatus("Done", "done", false) === "Done", "statusCategory 'done' maps to Done");
  ok("Jira mapping", mapStatus("Blocked", "indeterminate", false) === "Blocked", "a status name containing 'blocked' overrides the category");
  ok("Jira mapping", mapStatus("In Progress", "indeterminate", true) === "Blocked", "the Jira 'flagged' field forces Blocked regardless of status name");
  ok("Jira mapping", mapStatus("In Review", "indeterminate", false) === "In Review", "a status name containing 'review' maps to In Review");
  ok("Jira mapping", isBlockedByHeuristic(undefined, true) === true, "flagged alone is enough to be considered blocked");

  ok("Jira mapping", mapWorkItemType("Bug", []) === "bug", "issuetype Bug maps to bug");
  ok("Jira mapping", mapWorkItemType("Story", []) === "story", "issuetype Story maps to story");
  ok("Jira mapping", mapWorkItemType("Task", []) === "task", "issuetype Task maps to task");
  ok("Jira mapping", mapWorkItemType("Bug", ["production"]) === "production-issue", "a 'production' label upgrades a Bug to production-issue");
  ok("Jira mapping", mapWorkItemType(undefined, []) === "task", "missing issuetype defaults to task rather than throwing");
}


// ===== Jira normalization =====
{
  const issue = makeJiraIssue();
  const { workItem } = normalizeIssue(issue, { baseUrl: "https://acme.atlassian.net", today: TODAY });
  ok("Jira normalization", workItem.key === "JPMC-123" && workItem.title === "Fix checkout bug", "issue.key/summary map to WorkItem.key/title");
  ok("Jira normalization", workItem.owner === "Jane Doe", "assignee.displayName maps to owner");
  ok("Jira normalization", workItem.dueDate === "2026-09-03", "duedate maps straight through (already YYYY-MM-DD)");
  ok("Jira normalization", workItem.priority === "P2", "priority.name is mapped via mapPriority()");
  ok("Jira normalization", workItem.fixVersion === "2026.09", "fixVersions[0].name maps to fixVersion");
  ok("Jira normalization", workItem.sourceType === "jira" && workItem.sourceId === "JPMC-123", "source attribution is set");
  ok("Jira normalization", workItem.sourceUrl === "https://acme.atlassian.net/browse/JPMC-123", "sourceUrl is constructed from the real configured base URL");
  ok("Jira normalization", workItem.businessImpact === undefined, "business impact is never inferred from Jira priority (§17)");
  ok("Jira normalization", workItem.createdDate === "2026-08-01" && workItem.lastUpdated === "2026-08-27", "created/updated timestamps truncate to date-only");

  const noBaseUrl = normalizeIssue(issue, { today: TODAY });
  ok("Jira normalization", noBaseUrl.workItem.sourceUrl === undefined, "sourceUrl is never fabricated when no base URL is configured");

  // Missing fields (§29, §17)
  const bare = makeJiraIssue({ key: "JPMC-999", assignee: null, duedate: null, priority: null, fixVersions: [], labels: undefined });
  const { workItem: bareItem } = normalizeIssue(bare, { today: TODAY });
  ok("Missing fields", bareItem.owner === undefined, "missing assignee -> owner undefined, not fabricated");
  ok("Missing fields", bareItem.dueDate === undefined, "missing duedate -> dueDate undefined");
  ok("Missing fields", bareItem.fixVersion === undefined, "missing fixVersions -> fixVersion undefined");
  ok("Missing fields", bareItem.priority === "P3", "missing priority -> neutral P3 default");

  // Blocked-by dependency mapping
  const blockedIssue = makeJiraIssue({
    key: "JPMC-500",
    status: { name: "In Progress", statusCategory: { key: "indeterminate" } },
    issuelinks: [
      {
        type: { name: "Blocks", inward: "is blocked by", outward: "blocks" },
        inwardIssue: { key: "JPMC-100", fields: { summary: "Infra dependency", status: { name: "In Progress", statusCategory: { key: "indeterminate" } } } },
      },
    ],
  });
  const { workItem: blockedItem, dependencies } = normalizeIssue(blockedIssue, { today: TODAY });
  ok("Jira normalization", dependencies.length === 1 && dependencies[0].description.includes("JPMC-100"), "a 'Blocks' issuelink with an inwardIssue becomes a Dependency record");
  ok("Jira normalization", dependencies[0].status === "unresolved", "a not-done blocking issue produces an unresolved dependency");
  ok("Jira normalization", blockedItem.dependencyIds.includes(dependencies[0].id), "the WorkItem references the dependency it produced");

  // Multiple issues at once
  const { workItems } = normalizeIssues([issue, bare, blockedIssue], { today: TODAY });
  ok("Jira normalization", workItems.length === 3, "normalizeIssues processes a batch of fixtures");
}


// ===== Malformed Jira responses (schema validation) =====
{
  ok("Malformed Jira responses", jiraIssueSchema.safeParse({ key: "X-1", fields: {} }).success, "a minimal-but-valid issue (empty fields) validates");
  ok("Malformed Jira responses", !jiraIssueSchema.safeParse({ fields: {} }).success, "an issue with no key is rejected");
  ok("Malformed Jira responses", !jiraIssueSchema.safeParse("not an object").success, "a non-object payload is rejected rather than crashing the mapper");
  ok("Malformed Jira responses", jiraSearchResponseSchema.safeParse({ issues: [], startAt: 0, maxResults: 50, total: 0 }).success, "an empty-project search response validates");
  ok("Malformed Jira responses", !jiraSearchResponseSchema.safeParse({}).success, "a response missing the 'issues' array entirely is rejected, not silently treated as zero results");
  ok("Malformed Jira responses", jiraSearchResponseSchema.safeParse({ issues: [] }).success, "issues:[] with no other fields still validates (startAt/maxResults/total are genuinely optional)");
}


// ===== Pagination, incremental sync, rate-limit handling (dependency-injected fetch) =====
{
  const config = { baseUrl: "https://acme.atlassian.net", email: "ba@acme.com", apiToken: "x" };

  // 3-page fixture: 50 + 50 + 20 = 120 total issues.
  const pages = [50, 50, 20];
  let callCount = 0;
  // V2.2.2 — fetchJiraIssuesWith now tries POST /rest/api/3/search/jql first; these mocks
  // only model the classic startAt-based endpoint, so they report 404 on the replacement to
  // exercise the (still-real, still-tested) fallback path — see jira/http.ts.
  const paginatedFetch: FetchLike = async (url) => {
    if (url.includes("/search/jql")) return { ok: false, status: 404, json: async () => ({}) };
    callCount++;
    const startAt = Number(new URL(url).searchParams.get("startAt"));
    const pageIndex = startAt / JIRA_PAGE_SIZE;
    const pageSize = pages[pageIndex] ?? 0;
    const issues = Array.from({ length: pageSize }, (_, i) => makeJiraIssue({ key: `JPMC-${startAt + i}` }));
    return { ok: true, status: 200, json: async () => ({ issues, startAt, maxResults: JIRA_PAGE_SIZE, total: 120 }) };
  };
  const paged = await fetchJiraIssuesWith(paginatedFetch, config, {});
  ok("Pagination", paged.ok && paged.recordsFetched === 120, `pagination collects all 120 issues across pages (got ${paged.ok ? paged.recordsFetched : "error"})`);
  ok("Pagination", callCount === 3, `pagination stops once startAt reaches total — exactly 3 page requests (got ${callCount})`);

  // Incremental sync JQL
  ok("Incremental sync", buildIssuesJql({ sinceIso: "2026-08-01" }).includes('updated >= "2026-08-01"'), "sinceIso produces an 'updated >=' JQL clause");
  ok("Incremental sync", buildIssuesJql({ projectKeys: ["JPMC", "WF"] }).includes('project in ("JPMC","WF")'), "projectKeys produces a 'project in (...)' JQL clause");
  ok("Incremental sync", buildIssuesJql({}) === "project is not EMPTY order by updated asc", "no options -> a full, unscoped sync JQL that still satisfies Jira's bounded-query requirement (see V2.2.4)");

  // Rate limiting / error classification
  const rateLimited: FetchLike = async () => ({ ok: false, status: 429, json: async () => ({}) });
  const rateLimitedResult = await fetchJiraIssuesWith(rateLimited, config, {});
  ok("Rate-limit handling", !rateLimitedResult.ok && rateLimitedResult.errorKind === "rate-limited", "a 429 response is classified as rate-limited, not a generic failure");

  const authFailed: FetchLike = async () => ({ ok: false, status: 401, json: async () => ({}) });
  ok("Jira error states", (await fetchJiraProjectsWith(authFailed, config)).ok === false, "a 401 fails the projects fetch");
  const authResult = await fetchJiraIssuesWith(authFailed, config, {});
  ok("Jira error states", !authResult.ok && authResult.errorKind === "auth-failure", "401 classified as auth-failure");

  const forbidden: FetchLike = async () => ({ ok: false, status: 403, json: async () => ({}) });
  const forbiddenResult = await fetchJiraIssuesWith(forbidden, config, {});
  ok("Jira error states", !forbiddenResult.ok && forbiddenResult.errorKind === "permission-failure", "403 classified as permission-failure");

  ok("Jira error states", classifyHttpError(500).errorKind === "unknown", "an unrecognized status code classifies as 'unknown', not silently ignored");

  // Malformed response mid-pagination
  const malformedMidway: FetchLike = async (url) => {
    if (url.includes("/search/jql")) return { ok: false, status: 404, json: async () => ({}) };
    const startAt = Number(new URL(url).searchParams.get("startAt"));
    if (startAt === 0) return { ok: true, status: 200, json: async () => ({ issues: [makeJiraIssue()], startAt: 0, maxResults: 50, total: 100 }) };
    return { ok: true, status: 200, json: async () => ({ garbage: "not a search response" }) };
  };
  const malformedResult = await fetchJiraIssuesWith(malformedMidway, config, {});
  ok("Pagination failure", !malformedResult.ok && malformedResult.errorKind === "malformed-response", "a malformed page mid-pagination fails cleanly rather than returning partial/corrupt data");

  // Network failure
  const networkFail: FetchLike = async () => {
    throw new Error("fetch failed");
  };
  const networkResult = await fetchJiraIssuesWith(networkFail, config, {});
  ok("Jira error states", !networkResult.ok && networkResult.errorKind === "network-error", "a thrown network error is caught and classified, never left to crash the caller");
}


// ===== Multiple projects / multiple clients, Fix Version mapping =====
{
  const jiraProjects = [
    { key: "JPMC", name: "JPMC Digital Onboarding" },
    { key: "JPMCPAY", name: "JPMC Payments" },
    { key: "WF", name: "Wells Fargo Rollout" },
  ];
  const unmapped = normalizeProjects(jiraProjects, { today: TODAY });
  ok("Multiple projects", unmapped.projects.length === 3, "three Jira projects normalize to three Project records");
  ok("Multiple clients", unmapped.clients.length === 3, "without a client mapping, each Jira project defaults to its own client (1:1, never assumed otherwise)");

  const mapped = normalizeProjects(jiraProjects, { today: TODAY, projectToClient: { JPMC: "JPMC", JPMCPAY: "JPMC", WF: "Wells Fargo" } });
  ok("Multiple clients", mapped.clients.length === 2, "a project->client mapping lets one client own multiple Jira projects (§8)");
  ok("Multiple clients", clientIdForProjectKey("JPMC", { JPMC: "JPMC", JPMCPAY: "JPMC" }) === clientIdForProjectKey("JPMCPAY", { JPMC: "JPMC", JPMCPAY: "JPMC" }), "two projects mapped to the same client name resolve to the same clientId");
}


// ===== Global filters =====
{
  const { current } = buildDemoData(TODAY);
  const byClient = applyFilters(current, { clientId: "c-jpmc" }, TODAY);
  ok("Global filters", byClient.workItems.every((w) => w.clientId === "c-jpmc"), "clientId filter scopes work items to that client only");
  ok("Global filters", byClient.workItems.length > 0 && byClient.workItems.length < current.workItems.length, "client filter actually narrows the dataset (not a no-op)");

  const byVersion = applyFilters(current, { fixVersion: "2026.09" }, TODAY);
  ok("Global filters", byVersion.workItems.every((w) => w.fixVersion === "2026.09"), "fixVersion filter scopes to that release only");

  const noFilters = applyFilters(current, {}, TODAY);
  ok("Global filters", noFilters.workItems.length === current.workItems.length, "no active filters returns the data unchanged");

  const versions = availableFixVersions(current);
  ok("Global filters", versions.includes("2026.09"), "availableFixVersions surfaces the fix versions present in the data");
}


// ===== Data freshness =====
{
  const now = Date.now();
  ok("Data freshness", computeFreshness(new Date(now - 5 * 60_000).toISOString(), now) === "fresh", "5 minutes old is fresh (<30min)");
  ok("Data freshness", computeFreshness(new Date(now - 90 * 60_000).toISOString(), now) === "aging", "90 minutes old is aging (30min-4h)");
  ok("Data freshness", computeFreshness(new Date(now - 5 * 3_600_000).toISOString(), now) === "stale", "5 hours old is stale (>4h)");
  ok("Data freshness", computeFreshness(undefined, now) === "unknown", "no sync timestamp at all is 'unknown', never presented as fresh");
}


// ===== V2.24 — Automatic Jira Sync Reliability: shouldAutoSyncJira's pure eligibility gate.
// Phase 2 audit root cause: the scheduled cron (vercel.json / .github/workflows/sync.yml)
// reaches jira/sync/route.ts and genuinely fetches live Jira data, but that route is
// stateless-per-request (see its own top comment) — nothing persists the result anywhere the
// browser later reads, so a cron-triggered "sync" never actually refreshed what the user
// sees. Manual "Sync Now" only ever worked because it runs INSIDE the browser tab and calls
// store.syncJira() directly, which merges straight into this app's one real persistent store
// (IndexedDB/localStorage). The fix (auto-sync.ts) reuses that exact same store.syncJira()
// call automatically, from the browser, on the schedule this gate decides — no second sync
// implementation, no new server-side Jira data store. =====
{
  const now = Date.now();
  const fresh: JiraSyncState = { lastSyncStatus: "success", lastSyncCompletedAt: new Date(now - 5 * 60_000).toISOString() };
  const aging: JiraSyncState = { lastSyncStatus: "success", lastSyncCompletedAt: new Date(now - 90 * 60_000).toISOString() };
  const stale: JiraSyncState = { lastSyncStatus: "success", lastSyncCompletedAt: new Date(now - 5 * 3_600_000).toISOString() };
  const never: JiraSyncState = { lastSyncStatus: "never" };
  const failedButPreviouslyAging: JiraSyncState = { lastSyncStatus: "failed", lastSyncCompletedAt: new Date(now - 90 * 60_000).toISOString(), lastSyncError: "network blip" };

  ok("V2.24 Auto Sync gate", shouldAutoSyncJira("jira", aging, false, now) === true, "aging (30min-4h) Jira data with dataSource jira, not mid-sync, is eligible for an automatic refresh");
  ok("V2.24 Auto Sync gate", shouldAutoSyncJira("jira", stale, false, now) === true, "stale (>4h) data is equally eligible");
  ok("V2.24 Auto Sync gate", shouldAutoSyncJira("jira", fresh, false, now) === false, "data still 'fresh' (<30min) is NOT re-synced — reuses freshness.ts's own threshold rather than a second invented cadence, avoiding excessive Jira API calls");
  ok("V2.24 Auto Sync gate", shouldAutoSyncJira("jira", aging, true, now) === false, "never overlaps an already-in-flight sync (manual or automatic) — isSyncing=true is always a no-op regardless of freshness");
  ok("V2.24 Auto Sync gate", shouldAutoSyncJira("demo", aging, false, now) === false, "Demo data source is never auto-synced — this capability is Jira-only, exactly like every other Jira-specific feature in this app");
  ok("V2.24 Auto Sync gate", shouldAutoSyncJira("local-import", aging, false, now) === false, "Local Import is never auto-synced either");
  ok(
    "V2.24 Auto Sync gate",
    shouldAutoSyncJira("jira", never, false, now) === false,
    "lastSyncStatus 'never' (this install has never completed a real Jira sync) is NEVER auto-synced — the first-ever sync against a real Jira instance stays an explicit, confirmed user action (data-settings/page.tsx's existing pendingFirstSync gate, V2.1 §8); automatic sync only ever keeps an already-consented connection fresh, never initiates the first one"
  );
  ok(
    "V2.24 Auto Sync gate",
    shouldAutoSyncJira("jira", failedButPreviouslyAging, false, now) === true,
    "a previously FAILED sync (e.g. a transient network blip) with real aging data underneath is still eligible for the next automatic attempt — a failure must not permanently wedge auto-sync off"
  );
}


// ===== V2.25 Task 2 — shouldAutoGenerateDailyReport's pure eligibility gate (auto-daily-report.ts). =====
{
  ok("V2.25 Auto Daily Report gate", shouldAutoGenerateDailyReport("2026-06-15", {}) === true, "no report has ever been generated — eligible");
  ok(
    "V2.25 Auto Daily Report gate",
    shouldAutoGenerateDailyReport("2026-06-15", { "2026-06-14": { date: "2026-06-14", generatedAt: "x", events: [] } }) === true,
    "the most recently generated report is from a previous day (the day rolled over since) — eligible"
  );
  ok(
    "V2.25 Auto Daily Report gate",
    shouldAutoGenerateDailyReport("2026-06-15", { "2026-06-15": { date: "2026-06-15", generatedAt: "x", events: [] } }) === false,
    "today's report already exists — not eligible (avoids needlessly regenerating on every page mount within the same day)"
  );
  ok(
    "V2.25 Auto Daily Report gate",
    shouldAutoGenerateDailyReport("2026-06-15", { "2026-06-10": { date: "2026-06-10", generatedAt: "x", events: [] }, "2026-06-14": { date: "2026-06-14", generatedAt: "x", events: [] } }) === true,
    "correctly finds the MOST RECENT report among several, not just any key present in the map"
  );
}


// ===== Release readiness =====
{
  const readyItems = [
    makeItem({ id: "r1", fixVersion: "2027.01", status: "Done" }),
    makeItem({ id: "r2", fixVersion: "2027.01", status: "Done" }),
  ];
  const readyData = { ...emptyData(), workItems: readyItems };
  const readyHealth = computeReleaseHealth(readyData, "2027.01", TODAY);
  ok("Release readiness", readyHealth.readiness === "READY", `100% complete, 0 blocked/overdue/deps -> READY (got ${readyHealth.readiness})`);

  const notReadyItems = [
    makeItem({ id: "n1", fixVersion: "2027.02", status: "Not Started", blocked: true }),
    makeItem({ id: "n2", fixVersion: "2027.02", status: "Not Started", blocked: true }),
    makeItem({ id: "n3", fixVersion: "2027.02", status: "Not Started", blocked: true }),
  ];
  const notReadyHealth = computeReleaseHealth({ ...emptyData(), workItems: notReadyItems }, "2027.02", TODAY);
  ok("Release readiness", notReadyHealth.readiness === "NOT_READY", `0% complete + 3 blocked -> NOT_READY (got ${notReadyHealth.readiness})`);

  const atRiskItems = [
    makeItem({ id: "a1", fixVersion: "2027.03", status: "Done" }),
    makeItem({ id: "a2", fixVersion: "2027.03", status: "In Progress", blocked: true }),
  ];
  const atRiskHealth = computeReleaseHealth({ ...emptyData(), workItems: atRiskItems }, "2027.03", TODAY);
  ok("Release readiness", atRiskHealth.readiness === "AT_RISK", `50% complete + 1 blocked -> AT_RISK, the documented middle band (got ${atRiskHealth.readiness})`);

  const { current: demoCurrent } = buildDemoData(TODAY);
  const allReleases = computeAllReleaseHealth(demoCurrent, TODAY);
  ok("Release readiness", allReleases.some((r) => r.fixVersion === "2026.09"), "computeAllReleaseHealth finds the demo data's seeded fix version");
}


// ===== Meaningful change detection still works on Jira-normalized data =====
{
  const before = normalizeIssue(makeJiraIssue({ status: { name: "To Do", statusCategory: { key: "new" } } }), { today: TODAY }).workItem;
  const after = normalizeIssue(makeJiraIssue({ status: { name: "Blocked", statusCategory: { key: "indeterminate" } } }), { today: TODAY }).workItem;
  const previous = toSnapshot({ ...emptyData(), workItems: [before] }, "2026-06-14");
  const changes = detectChanges(previous, { ...emptyData(), workItems: [after] }, TODAY);
  ok("Change detection (Jira)", changes.some((c) => c.field === "Status"), "the existing change-detection engine works unchanged on Jira-normalized WorkItems — no engine changes were needed");
}


// ===== AI Context Builder — removed in C1 (never used by any AI call; see types.ts) =====
{
  ok("AI context builder (removed)", !fs.existsSync(path.join(process.cwd(), "src/lib/command-center/ai-context.ts")), "ai-context.ts is gone — every AI task builds its own task-scoped prompt (ai/prompts/*)");
  const promptSrc = fs.readdirSync(path.join(process.cwd(), "src/lib/command-center/ai/prompts")).map((f) => fs.readFileSync(path.join(process.cwd(), "src/lib/command-center/ai/prompts", f), "utf8")).join("\n");
  ok("AI context builder (removed)", !/apiToken|JIRA_API_TOKEN|ANTHROPIC_API_KEY/.test(promptSrc), "no prompt builder ever references a credential field or env var name");
}


// ===== Natural-language query routing =====
{
  const { current: qData } = buildDemoData(TODAY);
  const qDerived = deriveData(qData, null, TODAY);

  ok("NL query routing", classifyQuery("What's blocking JPMC?", qData).intent === "blocking", "'what's blocking X' routes to the blocking intent");
  ok("NL query routing", classifyQuery("What changed today?", qData).intent === "changed-today", "'what changed' routes to the changed-today intent");
  ok("NL query routing", classifyQuery("Show me risks for WF.", qData).intent === "risks-for", "'risks for X' routes to the risks-for intent");
  ok("NL query routing", classifyQuery("What should I do in the next 30 minutes?", qData).intent === "next-actions" && classifyQuery("What should I do in the next 30 minutes?", qData).minutes === 30, "'what should I do in N minutes' routes to next-actions with the parsed minute budget");
  ok("NL query routing", classifyQuery("Which client needs attention?", qData).intent === "client-attention", "'which client needs attention' routes to the client-attention intent");
  ok("NL query routing", classifyQuery("asdkjaskdj random text", qData).intent === "unrecognized", "unrecognized input never gets silently mapped to a random intent");

  const blockingRoute = classifyQuery("What's blocking JPMC?", qData);
  const blockingAnswer = answerFromRoute(blockingRoute, qData, qDerived, TODAY, "demo");
  ok("NL query routing", blockingAnswer.facts.length > 0 && blockingAnswer.evidence.length > 0, "the blocking intent for JPMC (which has blocked items in demo data) returns real facts and evidence");

  const mock = new MockAIProvider();
  const answered = await mock.answerQuery("What's blocking JPMC?", blockingAnswer.facts, blockingAnswer.evidence, blockingAnswer.recommendedAction);
  ok("NL query routing", answered.evidence === blockingAnswer.evidence, "answerQuery narrates the given evidence without altering it");
  ok("AI source attribution", answered.evidence.every((e) => !!e.content), "every evidence entry returned to the UI carries inspectable content");

  const emptyAnswer = await mock.answerQuery("What's blocking Diners?", [], [], "");
  ok("NL query routing", emptyAnswer.insufficientEvidence === true, "a query with no retrieved facts is answered honestly, not guessed");
}


// ===== Jira write-back extension point (disabled) =====
{
  const provider = new DisabledJiraActionProvider();
  let threw = 0;
  const calls = [
    () => provider.updateIssue("JPMC-1", {}),
    () => provider.addComment("JPMC-1", "hi"),
    () => provider.transitionIssue("JPMC-1", "31"),
    () => provider.assignIssue("JPMC-1", "acc-1"),
  ];
  for (const call of calls) {
    try {
      await call();
    } catch {
      threw++;
    }
  }
  ok("Human-in-the-loop", threw === calls.length, "every JiraActionProvider method rejects — no write-back is possible even if called by mistake");
}


// ===== Demo fallback / Jira-unavailable fallback / sync failure preserves state =====
{
  const fakeStorage = new Map<string, string>();
  (globalThis as unknown as { window: unknown }).window = {
    localStorage: {
      getItem: (k: string) => (fakeStorage.has(k) ? fakeStorage.get(k)! : null),
      setItem: (k: string, v: string) => { fakeStorage.set(k, v); },
      removeItem: (k: string) => { fakeStorage.delete(k); },
    },
  };

  commandCenterStore.loadDemoData();
  ok("Demo fallback", commandCenterStore.getSnapshot().dataSource === "demo", "the store defaults to (and after loadDemoData, remains) the demo data source");
  const workItemCountBefore = commandCenterStore.getSnapshot().data.workItems.length;

  // No dev server is running in this test process, so JiraDataSource.sync() will hit a
  // real network/URL-parsing failure — this exercises the actual failure path, not a mock.
  const syncResult = await commandCenterStore.syncJira();
  ok("Jira unavailable fallback", syncResult.ok === false, "syncJira() reports failure rather than throwing when the sync endpoint is unreachable");
  ok("Sync safety", commandCenterStore.getSnapshot().data.workItems.length === workItemCountBefore, "a failed sync never touches existing work-item data (§12 sync safety)");
  ok("Sync safety", commandCenterStore.getSnapshot().jiraSync.lastSyncStatus === "failed", "jiraSync bookkeeping records the failure");
  ok("Sync safety", commandCenterStore.getSnapshot().dataSource === "demo", "a failed sync does not switch the active data source to jira");

  const directSourceResult = await new JiraDataSource().sync();
  ok("Jira unavailable fallback", directSourceResult.ok === false && !!directSourceResult.errorKind, "JiraDataSource itself resolves with a classified failure rather than throwing");

  delete (globalThis as unknown as { window?: unknown }).window;
}


// ===== Credential safety — no client-side API token exposure (§33) =====
{
  const repoRoot = path.resolve(process.cwd());
  const clientDirs = ["src/app", "src/components", "src/lib/command-center"];
  const forbidden = [/process\.env\.JIRA_API_TOKEN/, /process\.env\.ANTHROPIC_API_KEY/, /process\.env\.JIRA_EMAIL/];
  const serverOnlyPaths = [path.join("src", "lib", "server"), path.join("src", "app", "api")];

  function walk(dir: string, out: string[]) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full, out);
      else if (/\.(ts|tsx)$/.test(entry.name)) out.push(full);
    }
  }

  const files: string[] = [];
  for (const dir of clientDirs) {
    const abs = path.join(repoRoot, dir);
    if (fs.existsSync(abs)) walk(abs, files);
  }
  const violations = files
    .filter((f) => !serverOnlyPaths.some((p) => f.includes(p)))
    .filter((f) => forbidden.some((re) => re.test(fs.readFileSync(f, "utf8"))));

  ok("Credential safety", violations.length === 0, `no client-reachable file references a raw credential env var (violations: ${violations.join(", ") || "none"})`);

  const jiraClientSrc = fs.readFileSync(path.join(repoRoot, "src/lib/server/jira-client.ts"), "utf8");
  ok("Credential safety", jiraClientSrc.includes('import "server-only"'), "the one file that reads real Jira credentials is marked server-only, enforced at build time");
}
