"use client";

// V2.25 Task 4 — Setup Health checklist. Confirmed real gap: several capabilities fail SILENTLY
// when a piece of configuration is missing, with nothing in the UI ever saying so:
//   - No Jira account ID configured (Data & Settings' "Who are you?" panel) means Mention/
//     Assignment tracking is a complete no-op — there's nothing to match comments/assignees
//     against (see jira/mentions.ts, assignment-detection.ts).
//   - An unclassified ("UNKNOWN") Jira status means every ticket currently sitting in that
//     status is correctly, conservatively excluded from Action Plan/Priorities/personal-work
//     surfaces (isPersonalWorkEligible's own §10 rule) — but that ticket then looks like it
//     simply vanished, with no visible reason, unless the user happens to open the Work
//     Relevance Policy in Data & Settings.
//   - No SLACK_WEBHOOK_URL, or no PERSONAL_JIRA_ACCOUNT_ID + Vercel KV, means real-time notify
//     only ever fires while a browser tab is open (see README's Server-Side Real-Time Notify
//     section) — nothing tells the user this is the case.
//
// This banner surfaces exactly the unresolved items, reusing the same store/derived data every
// other trust surface already reads (state.personalIdentity, workRelevanceIndex over
// filteredData, the notify status endpoint) — never a new source of truth, never new persisted
// state. Each row disappears the moment its underlying condition is resolved (no static list).
//
// computeSetupHealthRows is split out as a pure function — same "decision function separate
// from the thin UI/orchestration wrapper" discipline auto-sync.ts's shouldAutoSyncJira and
// auto-daily-report.ts's shouldAutoGenerateDailyReport already follow — so every show/hide
// condition is directly unit-testable without needing a DOM/React renderer.

import { useEffect, useState } from "react";
import Link from "next/link";
import { useCommandCenter } from "./use-command-center";
import { countUnclassifiedJiraStatuses, listUnclassifiedJiraStatuses, type WorkRelevanceIndex } from "@/lib/command-center/jira/work-relevance";
import { checkSlackNotifyStatus, type SlackNotifyStatus } from "@/lib/command-center/notify-client";
import { checkAppStateSyncStatus } from "@/lib/command-center/app-state-sync";
import { isDevicePaired } from "@/lib/command-center/device-pairing";
import { checkAiModelStatus } from "@/lib/command-center/ai/claude-provider";
import { isOlderThanDays } from "@/lib/command-center/backup";
import { useCrossDeviceSyncActive } from "./BackupReminder";
import type { CommandCenterData, DataSourceType, PersonalIdentity } from "@/lib/command-center/types";

/** C4 — additional, independently-loaded facts. Every field optional: undefined/null means
 *  "not known yet" and never produces a row. */
export interface SetupHealthExtras {
  /** Cross-device sync: the user turned it on (this device holds a pairing secret) or this
   *  device has synced before; and what the server says (null = still loading). */
  crossDevice?: { enabledOrEverPaired: boolean; status: { configured: boolean; paired: boolean } | null };
  /** Whether a Jira sprint custom field id is set in Data & Settings. */
  sprintFieldMapped?: boolean;
  /** The AI endpoint's status (null = still loading / unreachable). */
  ai?: { available: boolean; modelFromEnv?: boolean; fastModelFromEnv?: boolean; model?: string; fastModel?: string } | null;
  /** E1 — last backup download and whether cross-device sync (configured + paired) is active
   *  (null = still loading). */
  backup?: { lastBackupAt?: string; crossDeviceActive: boolean | null; isDemo: boolean; now: Date };
}

export interface SetupHealthRow {
  id: string;
  text: string;
}

/** Pure: given the same facts the store/derived data already expose, decides which rows (if
 *  any) belong in the banner. `notifyStatus === null` means "still loading" — never produces a
 *  false-positive "not configured" row for the brief moment before the real answer arrives. */
export function computeSetupHealthRows(
  personalIdentity: PersonalIdentity | undefined,
  dataSource: DataSourceType,
  data: CommandCenterData,
  workRelevanceIndex: WorkRelevanceIndex,
  notifyStatus: SlackNotifyStatus | null,
  extras: SetupHealthExtras = {}
): SetupHealthRow[] {
  const rows: SetupHealthRow[] = [];

  // C4 — only meaningful once Jira is the data source (demo/local-import have no accounts).
  if (dataSource === "jira" && !personalIdentity?.accountId) {
    rows.push({
      id: "identity",
      text: "No Jira account ID configured — Mention and Assignment tracking are completely off (nothing to match comments/assignees against).",
    });
  }

  if (dataSource === "jira") {
    const unclassifiedCount = countUnclassifiedJiraStatuses(data, workRelevanceIndex);
    if (unclassifiedCount > 0) {
      const names = listUnclassifiedJiraStatuses(data, workRelevanceIndex)
        .slice(0, 5)
        .map((s) => s.status);
      rows.push({
        id: "unclassified-status",
        text: `${unclassifiedCount} Jira status${unclassifiedCount === 1 ? "" : "es"} not yet classified in the Work Relevance Policy (${names.join(", ")}${unclassifiedCount > names.length ? ", …" : ""}) — tickets sitting in ${unclassifiedCount === 1 ? "this status" : "these statuses"} may look like they've simply disappeared from Action Plan/Priorities.`,
      });
    }
  }

  // C4 — cross-device sync, only for someone who actually uses (or used) it.
  const cd = extras.crossDevice;
  if (cd?.enabledOrEverPaired && cd.status && (!cd.status.configured || !cd.status.paired)) {
    rows.push({
      id: "cross-device",
      text: !cd.status.configured
        ? "Cross-device sync is not configured on the server (APP_STATE_SECRET + Vercel KV) — Complete/Skip/Block and reviews stay on this device only."
        : "This device is no longer paired for cross-device sync — re-pair it in Data & Settings, or changes made here won't reach your other devices.",
    });
  }

  if (dataSource === "jira" && extras.sprintFieldMapped === false) {
    rows.push({ id: "sprint-field", text: "Sprint field not mapped (optional) — set your Jira sprint field id in Data & Settings to group reports by sprint." });
  }

  if (extras.ai?.available && (!extras.ai.modelFromEnv || !extras.ai.fastModelFromEnv)) {
    const missing = [!extras.ai.modelFromEnv ? `ANTHROPIC_MODEL (using ${extras.ai.model ?? "the default"})` : "", !extras.ai.fastModelFromEnv ? `ANTHROPIC_MODEL_FAST (using ${extras.ai.fastModel ?? "the default"})` : ""].filter(Boolean);
    rows.push({ id: "ai-model", text: `AI model not set explicitly: ${missing.join(", ")} — set it on the server to pin which model answers.` });
  }

  // E1 — the only copy of this data is this browser's: say so once a week has passed.
  const b = extras.backup;
  if (b && b.crossDeviceActive === false && !b.isDemo && isOlderThanDays(b.lastBackupAt, b.now)) {
    rows.push({
      id: "backup",
      text: `No backup in the last 7 days and no cross-device sync — ${b.lastBackupAt ? `last backup ${new Date(b.lastBackupAt).toLocaleDateString()}` : "you have never downloaded a backup"}; clearing this browser's data would lose your ticket statuses, reports and history. Export a backup in Data & Settings.`,
    });
  }

  if (notifyStatus && !notifyStatus.serverSideNotifyActive) {
    rows.push({
      id: "notify",
      text: notifyStatus.configured
        ? "Real-time notify only works while a browser tab is open — configure PERSONAL_JIRA_ACCOUNT_ID + Vercel KV for unattended (cron-driven) notifications too."
        : "Slack notifications aren't configured at all (SLACK_WEBHOOK_URL) — you won't get mention/assignment alerts, even with a tab open.",
    });
  }

  return rows;
}

export function SetupHealthBanner() {
  const { state, filteredData, workRelevanceIndex } = useCommandCenter();
  // V2.11-style fetch-once-on-mount pattern, same as data-settings/page.tsx's own
  // checkSlackNotifyStatus().then(setStatus).
  const [notifyStatus, setNotifyStatus] = useState<SlackNotifyStatus | null>(null);
  useEffect(() => {
    let cancelled = false;
    checkSlackNotifyStatus().then((s) => {
      if (!cancelled) setNotifyStatus(s);
    });
    return () => {
      cancelled = true;
    };
  }, []);

  const [crossDeviceStatus, setCrossDeviceStatus] = useState<{ configured: boolean; paired: boolean } | null>(null);
  const [ai, setAi] = useState<SetupHealthExtras["ai"]>(null);
  const enabledOrEverPaired = state.loaded && (isDevicePaired() || !!state.lastAppStateSyncIso);
  useEffect(() => {
    let cancelled = false;
    checkAiModelStatus().then((s) => {
      if (!cancelled) setAi(s);
    });
    return () => {
      cancelled = true;
    };
  }, []);
  useEffect(() => {
    if (!enabledOrEverPaired) return;
    let cancelled = false;
    checkAppStateSyncStatus().then((s) => {
      if (!cancelled) setCrossDeviceStatus(s);
    });
    return () => {
      cancelled = true;
    };
  }, [enabledOrEverPaired]);

  const crossDeviceActive = useCrossDeviceSyncActive();

  if (!state.loaded) return null;

  const rows = computeSetupHealthRows(state.personalIdentity, state.dataSource, filteredData, workRelevanceIndex, notifyStatus, {
    crossDevice: { enabledOrEverPaired, status: crossDeviceStatus },
    sprintFieldMapped: !!state.jiraSprintFieldId,
    ai,
    backup: { lastBackupAt: state.lastBackupAt, crossDeviceActive, isDemo: state.isDemo, now: new Date() },
  });
  if (rows.length === 0) return null;

  return (
    <div className="mb-4 rounded-md border border-yellow/40 bg-yellow/10 px-4 py-3 text-sm text-text" role="alert">
      <p className="font-semibold text-yellow">
        ⚠ Setup Health — {rows.length} item{rows.length === 1 ? "" : "s"} need attention
      </p>
      <ul className="mt-1.5 list-inside list-disc space-y-1 text-text2">
        {rows.map((r) => (
          <li key={r.id}>{r.text}</li>
        ))}
      </ul>
      <p className="mt-2">
        <Link href="/data-settings" className="text-accent2 underline">
          Fix this in Data &amp; Settings
        </Link>
      </p>
    </div>
  );
}
